# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: John Pilbeam
email: Email - jpilbeam + gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#    © 2021, John Pilbeam
# More information about my projects and interests can be found on my [LinkedIn profile](http://uk.linkedin.com/pub/john-pilbeam/a/8a/655/)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnpilbeam.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jpilbeam
github_username: johnpilbeam

# Build settings
remote_theme: broccolini/swiss
# theme: minima
# https://github.com/jeromelachaud/freelancer-theme
# remote_theme: jeromelachaud/freelancer-theme
plugins:
  - jekyll-feed

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: white

# Other Swiss theme settings
#title: Swiss Jekyll Theme
description:  Thoughts on technology, libraries and higher education
github_repo: johnpilbeam.com # the GitHub repo name for your project


# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: jpilbeam

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
